config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :signers
  resources :survey_results
  resources :volunteers
  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: [:show, :edit, :update, :destroy]
  skip_before_filter  :verify_authenticity_token


  # GET /volunteers
  # GET /volunteers.json
  def index
    @volunteers = Volunteer.all
  end

  # GET /volunteers/1
  # GET /volunteers/1.json
  def show
  end

  # GET /volunteers/new
  def new
    @volunteer = Volunteer.new
  end

  # GET /volunteers/1/edit
  def edit
  end

  # POST /volunteers
  # POST /volunteers.json
  def create
    collected_data = JSON.parse params["collected_data"]
    if collected_data["confirmed"]
      new_volunteer_params = {
        name: collected_data["name"],
        twitter_handle: collected_data["other_contact"],
        mobile: collected_data["SRC"],
        note: collected_data["note"]
      }
      @volunteer = Volunteer.new(new_volunteer_params)
      respond_to do |format|
        if @volunteer.save
          render :nothing => true
        else
          render json: @volunteer.errors, status: :unprocessable_entity
        end
      end
    else
      render :nothing => true
    end
  end

  # PATCH/PUT /volunteers/1
  # PATCH/PUT /volunteers/1.json
  def update
    respond_to do |format|
      if @volunteer.update(volunteer_params)
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully updated.' }
        format.json { render :show, status: :ok, location: @volunteer }
      else
        format.html { render :edit }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1
  # DELETE /volunteers/1.json
  def destroy
    @volunteer.destroy
    respond_to do |format|
      format.html { redirect_to volunteers_url, notice: 'Volunteer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volunteer
      @volunteer = Volunteer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volunteer_params
      params.require(:volunteer).permit(:name, :twitter_handle, :mobile)
    end
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/_form.html.slim
= simple_form_for @volunteer, :html => { :class => 'form-horizontal' } do |f|
|   = f.input :name
|   = f.input :twitter_handle
|   = f.input :mobile
| |   .form-actions
    = f.button :submit, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), volunteers_path, :class => 'btn'
| 

app/views/volunteers/edit.html.slim
- model_class = Volunteer
.page-header
  h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/volunteers/index.html.slim
- model_class = Volunteer
.container.top-div
  .col-sm-12
    .row
      .page-header
        h1=t '.title', :default => model_class.model_name.human.pluralize
      table.table.table-striped
        thead
          tr
            th= model_class.human_attribute_name(:name)
            th= model_class.human_attribute_name(:twitter_handle)
            th= model_class.human_attribute_name(:mobile)
            th Signed Up
            th Notes
            th=t '.actions', :default => t("helpers.actions")
          tbody
            - @volunteers.each do |volunteer|
              tr
                td= link_to volunteer.name, volunteer_path(volunteer)
                td= volunteer.twitter_handle
                td= volunteer.mobile
                td= time_ago_in_words(volunteer.created_at)
                td= volunteer.note
                td
                  = link_to t('.edit', :default => t("helpers.links.edit")), edit_volunteer_path(volunteer), :class => 'btn btn-primary btn-xs'
                  | &#xA0;
                  = link_to t('.destroy', :default => t("helpers.links.destroy")), volunteer_path(volunteer), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn-xs'

      = link_to t('.new', :default => t("helpers.links.new")), new_volunteer_path, :class => 'btn btn-primary'

app/views/volunteers/new.html.slim
- model_class = Volunteer
.page-header
  h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/volunteers/show.html.slim
- model_class = Volunteer
.page-header
  h1=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @volunteer.name
p
  strong= model_class.human_attribute_name(:twitter_handle) + ':'
  br
  = @volunteer.twitter_handle
p
  strong= model_class.human_attribute_name(:mobile) + ':'
  br
  = @volunteer.mobile

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), volunteers_path, :class => 'btn'
  | &#xA0;
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_volunteer_path(@volunteer), :class => 'btn btn-primary'
  | &#xA0;
  = link_to t('.destroy', :default => t("helpers.links.destroy")), volunteer_path(@volunteer), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'