config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :signers
  resources :survey_results
  resources :volunteers
  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/survey_result.rb
class SurveyResult < ActiveRecord::Base
end

app/controllers/survey_results_controller.rb
class SurveyResultsController < ApplicationController
  before_action :set_survey_result, only: [:show, :edit, :update, :destroy]
  skip_before_filter  :verify_authenticity_token

  # GET /survey_results
  # GET /survey_results.json
  def index
    @survey_results = SurveyResult.all
  end

  # GET /survey_results/1
  # GET /survey_results/1.json
  def show
  end

  # GET /survey_results/new
  def new
    @survey_result = SurveyResult.new
  end

  # GET /survey_results/1/edit
  def edit
  end

  # POST /survey_results
  # POST /survey_results.json
  def create
    collected_data = JSON.parse params["collected_data"]
    new_survey_params = {
      liberty: collected_data["DATA_PROMPT_1"],
      sexy: collected_data["DATA_PROMPT_2"],
      mobile: collected_data["SRC"],
      wigs_wired: collected_data["DATA_PROMPT_3"]
    }
    @survey_result = SurveyResult.new(new_survey_params)
    respond_to do |format|
      if @survey_result.save
        render :nothing => true
      else
        render json: @survey_result.errors, status: :unprocessable_entity
      end
    end
  end

  # PATCH/PUT /survey_results/1
  # PATCH/PUT /survey_results/1.json
  def update
    respond_to do |format|
      if @survey_result.update(survey_result_params)
        format.html { redirect_to @survey_result, notice: 'Survey result was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_result }
      else
        format.html { render :edit }
        format.json { render json: @survey_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_results/1
  # DELETE /survey_results/1.json
  def destroy
    @survey_result.destroy
    respond_to do |format|
      format.html { redirect_to survey_results_url, notice: 'Survey result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_result
      @survey_result = SurveyResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_result_params
      params.require(:survey_result).permit(:mobile, :liberty, :sexy, :wigs_wired)
    end
end

app/helpers/survey_results_helper.rb
module SurveyResultsHelper
end

app/views/survey_results/_form.html.slim
= simple_form_for @survey_result, :html => { :class => 'form-horizontal' } do |f|
|   = f.input :mobile
|   = f.input :liberty
|   = f.input :sexy
|   = f.input :wigs_wired
| |   .form-actions
    = f.button :submit, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), survey_results_path, :class => 'btn'
| 

app/views/survey_results/edit.html.slim
- model_class = SurveyResult
.page-header
  h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/survey_results/index.html.slim
- model_class = SurveyResult
.container.top-div
  .col-sm-12
    .row
      .page-header
        h1=t '.title', :default => model_class.model_name.human.pluralize
      table.table.table-striped
        thead
          tr
            th= model_class.human_attribute_name(:id)
            th= model_class.human_attribute_name(:mobile)
            th= model_class.human_attribute_name(:liberty)
            th= model_class.human_attribute_name(:sexy)
            th= model_class.human_attribute_name(:wigs_wired)
            th= model_class.human_attribute_name(:created_at)
            th=t '.actions', :default => t("helpers.actions")
          tbody
            - @survey_results.each do |survey_result|
              tr
                td= link_to survey_result.id, survey_result_path(survey_result)
                td= survey_result.mobile
                td= survey_result.liberty
                td= survey_result.sexy
                td= survey_result.wigs_wired
                td=l survey_result.created_at
                td
                  = link_to t('.edit', :default => t("helpers.links.edit")), edit_survey_result_path(survey_result), :class => 'btn btn-primary btn-xs'
                  | &#xA0;
                  = link_to t('.destroy', :default => t("helpers.links.destroy")), survey_result_path(survey_result), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn-xs'

      = link_to t('.new', :default => t("helpers.links.new")), new_survey_result_path, :class => 'btn btn-primary'

app/views/survey_results/new.html.slim
- model_class = SurveyResult
.page-header
  h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/survey_results/show.html.slim
- model_class = SurveyResult
.page-header
  h1=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:mobile) + ':'
  br
  = @survey_result.mobile
p
  strong= model_class.human_attribute_name(:liberty) + ':'
  br
  = @survey_result.liberty
p
  strong= model_class.human_attribute_name(:sexy) + ':'
  br
  = @survey_result.sexy
p
  strong= model_class.human_attribute_name(:wigs_wired) + ':'
  br
  = @survey_result.wigs_wired

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), survey_results_path, :class => 'btn'
  | &#xA0;
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_survey_result_path(@survey_result), :class => 'btn btn-primary'
  | &#xA0;
  = link_to t('.destroy', :default => t("helpers.links.destroy")), survey_result_path(@survey_result), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'