config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :signers
  resources :survey_results
  resources :volunteers
  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
.container
  nav.navbar.navbar-inverse.navbar-fixed-top
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'We Need George in 1776', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Volunteers', volunteers_path %></li>
<li><%= link_to 'Events', events_path %></li>
<li><%= link_to 'Petition Signers', signers_path %></li>
<li><%= link_to 'Survey Results', survey_results_path %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Tadhack2015'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Tadhack2015'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/layouts/cyborg.html.slim
doctype 5
html(lang="en")
  head
    meta(charset="utf-8")
    meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title= content_for?(:title) ? yield(:title) : "tadhack2015"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "cyborg", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  body

    = yield

    /!
      | Javascripts
      | \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "cyborg"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/layouts/flatly.html.slim
doctype 5
html(lang="en")
  head
    meta(charset="utf-8")
    meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title= content_for?(:title) ? yield(:title) : "tadhack2015"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "flatly", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

    /!
      | Javascripts
      | \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "flatly"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/layouts/lumen.html.slim
doctype 5
html(lang="en")
  head
    meta(charset="utf-8")
    meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title= content_for?(:title) ? yield(:title) : "tadhack2015"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "lumen", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  body

    = yield

    /!
      | Javascripts
      | \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "lumen"
    = yield(:page_javascript) if content_for?(:page_javascript)